framework:
    messenger:
        failure_transport: failed

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - validation
                    - dispatch_after_current_bus
                    - doctrine_transaction

        transports:
            failed: 'doctrine://default?queue_name=failed'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: default

            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high

            async_priority_low:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: low

            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'test://'
                async_priority_high: 'test://'
                async_priority_low: 'test://'
